import turtle

screen = turtle.Screen()
screen.screensize(500,500)
screen.bgcolor("DarkSeaGreen3")

t = turtle.Turtle()
t.speed(0)
t.penup()
t.goto(-300,0)
t.pendown()
t.pencolor("white")
t.write("All about me presentation!",font=("Arial",40,"normal"),align="left")

t.penup()
t.goto(0, 200)
t.pendown()
screen.addshape("Mason.gif")
t.shape("Mason.gif")
t.stamp()
t.shape("classic")

t.penup()
t.goto(0, -200)
t.pendown()
screen.addshape("Turtle heart.gif")
t.shape("Turtle heart.gif")
t.stamp()
t.shape("classic")

t.begin_fill()
t.fillcolor("red")
t.pencolor("red")
t.penup()
t.goto(200,200,)
t.pendown()
t.circle(25)
t.end_fill()

t.penup()
t.goto(-150,50)
t.pendown()
t.write("Press Enter to Continue", font=("arial",20,"italic"),align="center")
round = input("Press Enter to Continue: ")
t.clear()
screen.bgcolor("yellow")

t.penup()
t.goto(-300,0)
t.pendown()
t.pencolor("black")
t.write("My Favorite Foods!",font=("Arial",50,"normal"),align="left")

t.penup()
t.goto(0, 200)
t.pendown()
screen.addshape("pizza roll.gif")
t.shape("pizza roll.gif")
t.stamp()
t.shape("classic")

t.penup()
t.goto(0,300)
t.pendown()
t.pencolor("black")
t.write("Pizza Roll",font=("Arial",20,"normal"),align="center")

t.penup()
t.goto(-100,-50)
t.pendown()
t.pencolor("black")
t.write("Pink Drink",font=("Arial",20,"normal"),align="center")

t.penup()
t.goto(-100, -200)
t.pendown()
screen.addshape("pink drink.gif")
t.shape("pink drink.gif")
t.stamp()
t.shape("classic")

t.penup()
t.goto(100,-50)
t.pendown()
t.pencolor("black")
t.write("Chickfila",font=("Arial",20,"normal"),align="center")

t.penup()
t.goto(100, -200)
t.pendown()
screen.addshape("chick.gif")
t.shape("chick.gif")
t.stamp()
t.shape("classic")

t.speed(0)
t.penup()
t.goto(-150,200)
t.setheading(135)
t.fillcolor("cyan")
t.pendown()
t.begin_fill()
t.forward(50)
t.left(50)
t.forward(50)
t.left(50)
t.forward(50)
t.left(50)
t.forward(50)
t.end_fill()

t.penup()
t.goto(-150,70)
t.pendown()
t.write("Press Enter to Continue", font=("arial",20,"italic"),align="center")
round = input("Press Enter to Continue: ")
t.clear()
screen.bgcolor("orange")

t.penup()
t.goto(0,0)
t.pendown()
t.pencolor("black")
t.write("My Hobbies",font=("Arial",50,"normal"),align="center")

t.penup()
t.goto(100,-50)
t.pendown()
t.pencolor("black")
t.write("Cooking",font=("Arial",20,"normal"),align="center")

t.penup()
t.goto(100, -200)
t.pendown()
screen.addshape("cheff.gif")
t.shape("cheff.gif")
t.stamp()
t.shape("classic")

t.penup()
t.goto(-200,100)
t.pendown()
t.pencolor("black")
t.write("Shopping",font=("Arial",20,"normal"),align="center")

t.penup()
t.goto(-200, 200)
t.pendown()
screen.addshape("shop.gif")
t.shape("shop.gif")
t.stamp()
t.shape("classic")

t.penup()
t.goto(-200,-50)
t.pendown()
t.pencolor("black")
t.write("Skiing",font=("Arial",20,"normal"),align="center")

t.penup()
t.goto(-200, -200)
t.pendown()
screen.addshape("x.gif")
t.shape("x.gif")
t.stamp()
t.shape("classic")

t.penup()
t.goto(100,100)
t.pendown()
t.pencolor("black")
t.write("Traveling",font=("Arial",20,"normal"),align="center")

t.penup()
t.goto(100, 225)
t.pendown()
screen.addshape("t.gif")
t.shape("t.gif")
t.stamp()
t.shape("classic")

t.penup()
t.goto(200,0)
t.pendown()
t.pencolor("black")
t.fillcolor("blue")
t.begin_fill()
t.goto(250,0)
t.goto(200,100)
t.goto(200,0)
t.end_fill()

t.penup()
t.goto(-150,70)
t.pendown()
t.write("Press Enter to Continue", font=("arial",20,"italic"),align="center")
round = input("Press Enter to Continue: ")
t.clear()
screen.bgcolor("green")

t = turtle.Turtle()
t.speed(0)
t.penup()
t.goto(-300,0)
t.pendown()
t.pencolor("white")
t.write("My favorite Movie!",font=("Arial",40,"normal"),align="left")

t.penup()
t.goto(-100, -150)
t.pendown()
screen.addshape("str.gif")
t.shape("str.gif")
t.stamp()
t.shape("classic")

t.penup()
t.goto(-200,200)
t.pendown()
t.pencolor("yellow")
t.goto(-200,200)
t.pensize(5)
t.goto(-200,200)
t.pensize(1)
t.penup()

#circle - radius
t.pencolor("orange")
t.fillcolor("orange")
t.begin_fill()
t.circle(25)
t.setheading(270)
t.circle(25)
t.setheading(90)
t.circle(25)
t.setheading(180)
t.circle(25)
t.end_fill()

t.penup()
t.goto(-200,190)
t.pendown()
t.setheading(0)
t.fillcolor("yellow")
t.begin_fill()
t.circle(15)
t.end_fill()

t.penup()
t.goto(220, -180)
t.pendown()
screen.addshape("movie2.gif")
t.shape("movie2.gif")
t.stamp()
t.shape("classic")

t.penup()
t.goto(-150,70)
t.pendown()
t.write("Press Enter to Continue", font=("arial",20,"italic"),align="center")
round = input("Press Enter to Continue: ")
t.clear()
screen.bgcolor("purple")

t = turtle.Turtle()
t.speed(0)
t.penup()
t.goto(-300,0)
t.pendown()
t.pencolor("white")
t.write("My favorite Sport!",font=("Arial",40,"normal"),align="left")

t.penup()
t.goto(0,-300)
t.pendown()
t.pencolor("black")
t.write("Competitive Dance",font=("Arial",20,"normal"),align="center")

t.penup()
t.goto(0, -140)
t.pendown()
screen.addshape("bdg.gif")
t.shape("bdg.gif")
t.stamp()
t.shape("classic")

t.fillcolor("green")
t.begin_fill()
t.penup()
t.goto(-250,-200)
t.pendown()
t.forward(100)
t.left(90)
t.forward(50)
t.left(90)
t.forward(100)
t.left(90)
t.forward(50)

t.end_fill()

t.penup()
t.goto(220, -180)
t.pendown()
screen.addshape("heart.gif")
t.shape("heart.gif")
t.stamp()
t.shape("classic")

turtle.done()